import { Event } from '../event'

const events_seed: Event[] = [
    {
        id: "xsfo8d0oqq-khdub0yfwq7-p1g6u901b7s",
        alias: 'evento-fullstack',
        password: 'password123',
        name: 'Evento de Desenvolvimento Fullstack',
        date: new Date('2024-12-01T10:00:00Z'),
        location: 'São Paulo, SP',
        description:
            'Um evento completo para aprender desenvolvimento fullstack do zero.',
        image: 'https://techcrunch.com/wp-content/uploads/2015/04/codecode.jpg?w=1024',
        backgroundImage:
            'https://images.prismic.io/vaultinum/0458a9f1-e149-4037-b9aa-aa4b4fb53c25_propriete-intellectuelle-code-source-protection-compressed.jpg?auto=compress,format&rect=0,0,2400,981&w=2400&h=981',
        expectedPublic: 200,
        guests: [
            {
                id: "0elbsyd4apoh-h8sdkolf7j-4oz2nwpe4kv",
                name: 'Alice Silva',
                email: 'alice@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 1,
            },
            {
                id: "1kef3myzf2k-w5q2ytgzjta-pyg3kqlb70r",
                name: 'Carlos Pereira',
                email: 'carlos@example.com',
                confirmed: false,
                companion: false,
                companionAmount: 0,
            },
            {
                id: "b5uglayto5w-vbfv53p9q4j-mbcf0urgbns",
                name: 'Beatriz Lima',
                email: 'beatriz@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 2,
            },
        ],
    },
    {
        id: "1xbb65p4919-yz75llwucsi-pjtidkui9r",
        alias: 'evento-js-avancado',
        password: 'js2024',
        name: 'Workshop Avançado de JavaScript',
        date: new Date('2024-11-20T15:00:00Z'),
        location: 'Rio de Janeiro, RJ',
        description: 'Um workshop avançado para programadores JavaScript.',
        image: 'https://www.datocms-assets.com/48401/1628644950-javascript.png?auto=format&fit=max&w=1200',
        backgroundImage:
            'https://blog.cronapp.io/wp-content/uploads/2020/09/javascript-1.jpg',
        expectedPublic: 100,
        guests: [
            {
                id: "2gzgsps30my-apmcg4g16zb-0eccn1r3ib5j",
                name: 'Eduardo Santos',
                email: 'eduardo@example.com',
                confirmed: true,
                companion: false,
                companionAmount: 0,
            },
            {
                id: "bk64t13dp7t-1rxen8us0ue-qnsujnx8ry8",
                name: 'Fernanda Costa',
                email: 'fernanda@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 1,
            },
        ],
    },
    {
        id: "5cea3lr5kbv-eol3ffzv2he-d8ayfuv2f8",
        alias: 'evento-dev-frontend',
        password: 'front123',
        name: 'Bootcamp de Desenvolvimento Frontend',
        date: new Date('2024-11-15T09:00:00Z'),
        location: 'Belo Horizonte, MG',
        description: 'Aprenda a criar interfaces incríveis e responsivas.',
        image: 'https://www.simplilearn.com/ice9/free_resources_article_thumb/recact_angular_vue.jpg',
        backgroundImage:
            'https://www.frontendmag.com/wp-content/uploads/2023/01/easiest-front-end-framework.jpeg',
        expectedPublic: 150,
        guests: [
            {
                id: "ohmxvi0diuk-ume17xfssh9-no6l8ggqph",
                name: 'Gabriela Rocha',
                email: 'gabriela@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 1,
            },
            {
                id: "qjjoitet7ih-7g778xbbfvp-c8mpuv69fs4",
                name: 'Hugo Nogueira',
                email: 'hugo@example.com',
                confirmed: false,
                companion: false,
                companionAmount: 0,
            },
            {
                id: "mn80n3hii9-we8qxdci5yc-j206wjqt0n",
                name: 'Isabela Martins',
                email: 'isabela@example.com',
                confirmed: true,
                companion: false,
                companionAmount: 0,
            },
        ],
    },
    {
        id: "smyn42mx0ek-2v1jlfnkzt8-qgehtyakm2l",
        alias: 'casamento-alberto-marina',
        password: 'casamento2024',
        name: 'Casamento do Alberto e Marina',
        date: new Date('2024-11-25T16:00:00Z'),
        location: 'Florianópolis, SC',
        description:
            'Celebração do casamento de Alberto e Marina com amigos e familiares.',
        image: 'https://i.em.com.br/IQ1l_dkc9VYK5P8PW-EaTphOuF4=/790x/smart/imgsapp.em.com.br/app/noticia_127983242361/2023/05/21/1496049/uma-cor-que-esta-totalmente-proibida-para-as-convidadas-de-acordo-com-a-etiqueta-de-casamento-e-o-branco-que-esta-reservado-para-as-noivas-a-nao-ser-que-o-casamento-seja-na-praia_1_55583.jpg',
        backgroundImage:
            'https://www.psicologo.com.br/wp-content/uploads/casamento-feliz-um-guia-para-casamentos-felizes.jpg',
        expectedPublic: 150,
        guests: [
            {
                id: "vsxuipt41v-eyt4lxjor1-021e33u7zn86",
                name: 'Bruno Cardoso',
                email: 'bruno@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 1,
            },
            {
                id: "0o8ymiaoz9kr-ut5sbu841vs-m313rreq02",
                name: 'Carla Mendes',
                email: 'carla@example.com',
                confirmed: true,
                companion: false,
                companionAmount: 0,
            },
        ],
    },
    {
        id: "sv8iwcoh5eo-2mll4uf6n4p-xsvz73usyjg",
        alias: 'aniversario-joao',
        password: 'joao2024',
        name: 'Aniversário do João - 30 Anos',
        date: new Date('2024-12-05T18:00:00Z'),
        location: 'Curitiba, PR',
        description:
            'Comemoração dos 30 anos de João com amigos próximos e familiares.',
        image: 'https://img.elo7.com.br/product/600x380/4C55C74/capa-painel-redondo-tema-feliz-aniversario-em-tecido-1-50m-festa.jpg',
        backgroundImage:
            'https://img.freepik.com/vetores-gratis/fundo-da-celebracao-dos-baloes-e-confetti_1048-2223.jpg',
        expectedPublic: 80,
        guests: [
            {
                id: "6sfxtwuruvj-94nfpnw9dtg-lhj1o5krvn",
                name: 'Maria Souza',
                email: 'maria@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 2,
            },
            {
                id: "4xnskd99a0w-b1un0dcrfpb-vvxkvlp2np",
                name: 'José Almeida',
                email: 'jose@example.com',
                confirmed: false,
                companion: false,
                companionAmount: 0,
            },
        ],
    },
    {
        id: "2i3piyf08y2-cya8nkjpyn-4p2rtv6hv8s",
        alias: 'inauguracao-loja-estrela',
        password: 'estrela2024',
        name: 'Inauguração da Loja Estrela',
        date: new Date('2024-12-10T09:00:00Z'),
        location: 'Porto Alegre, RS',
        description:
            'Evento de inauguração da nova loja Estrela com brindes e promoções.',
        image: 'https://cosmeticinnovation.com.br/wp-content/uploads/2018/01/estrela_cosmeticos.png',
        backgroundImage:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ-0_VdF_lcXATRHDUaaI0AQCt8R6Y_ShR3A&s',
        expectedPublic: 300,
        guests: [
            {
                id: "23jtegqfis9-3e3l6e6lewq-2s9o63twec5",
                name: 'Cláudia Lima',
                email: 'claudia@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 3,
            },
            {
                id: "vbo6te5rncn-b4xl9nxetu7-lbt3qd4hoji",
                name: 'Ricardo Barbosa',
                email: 'ricardo@example.com',
                confirmed: true,
                companion: false,
                companionAmount: 0,
            },
        ],
    },
    {
        id: "2ugtl8y77i3-1ivkxaoyevg-i5iw789dolc",
        alias: 'reuniao-familia-oliveira',
        password: 'familia2024',
        name: 'Reunião da Família Oliveira',
        date: new Date('2024-12-15T12:00:00Z'),
        location: 'Salvador, BA',
        description: 'Reunião de fim de ano da família Oliveira.',
        image: 'https://www.themonastery.org/assets/themonastery/blog/scaled/duggars.jpg',
        backgroundImage:
            'https://img.freepik.com/fotos-premium/ondas-abstratas-brilhantes-de-celebracao-do-arco-iris-fluem-suavemente-geradas-por-ia_188544-9530.jpg?semt=ais_hybrid',
        expectedPublic: 50,
        guests: [
            {
                id: "swcl7psspnn-jts1ym34ab-kzcivnlv3x8",
                name: 'Thiago Oliveira',
                email: 'thiago@example.com',
                confirmed: true,
                companion: true,
                companionAmount: 4,
            },
            {
                id: "vua2glibnc-0ztsrhu27j7-ax54zzrrj69",
                name: 'Letícia Oliveira',
                email: 'leticia@example.com',
                confirmed: true,
                companion: false,
                companionAmount: 0,
            },
        ],
    },
]

export default events_seed
